apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-operator
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: trivy-dojo-report-operator
    app.kubernetes.io/name: trivy-dojo-report-operator
  {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ports | toYaml | nindent 2 -}}