---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: mgmt
  name: trivy-dojo-report-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-dojo-report-role-cluster
rules:
  - apiGroups: [aquasecurity.github.io]
    resources: [vulnerabilityreports, rbacassessmentreports, configauditreports, infraassessmentreports, exposedsecretreports]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  - apiGroups: [""]
    resources: [events]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-dojo-report-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-dojo-report-role-cluster
subjects:
  - kind: ServiceAccount
    name: trivy-dojo-report-account
    namespace: "mgmt"
