name: Linting

on: [push, pull_request]

jobs:
  linting:
    # docs: https://github.com/telekom-mms/.github#python-linting
    uses: telekom-mms/.github/.github/workflows/python_linting.yml@5b1fd9ad47be83e2dbd0887abff9ece29e2e324f # main
